---
title: "area_change_slope_graph"
author: "Miranda Lupion"
date: "12/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
library(readr)
library(ggrepel)
library(tidyverse)
library(stringr)
library(scales)
theme_set((theme_classic()))
area_change <- read_csv("area_change_1818_1908.csv")

```


```{r, labels and data frame}
years <- 90

# Select the data for year 1 (1818)

year_1 <- area_change %>%
  filter(year == 1818) %>%
  select(percent_forested)

# Select the data for year 2 (1908)

year_2 <- area_change %>%
  filter(year == 1908) %>%
  select(percent_forested)


# Only select one set of districts 
# This is made possible because R is preserving the order of all these observations 

groups <- area_change %>%
  filter(year == 1818) %>%
  select(district)

# Put the selected data together into a single data frame

slope_data <- data.frame(year_1, year_2, groups) %>%
  rename(year_1 = percent_forested, year_2 = percent_forested.1, groups = district) %>%
  filter(groups != "All") %>%
  mutate(groups = str_remove(groups, " District"), pct_diff = year_2 - year_1) %>%
  
  # Coloring based on quantile breakdowns
  # quantile(slope_data$pct_diff)

  mutate(coloring = case_when(pct_diff > 0 ~ "green",
                              pct_diff >= -4.7 ~ "light red",
                              pct_diff >= -10.255 ~ "red",
                              pct_diff >= -23.5  ~ "dark red" ))

# Create the labels for the graphic

l11 <- paste0(slope_data$groups, ", ", slope_data$year_1, "%")

l13 <-paste0(slope_data$groups,", ", slope_data$year_2, "%")


```


```{r graphic}

# Slope data

ggplot(slope_data) + 
  
  # Segment codes
  
  geom_segment(aes(x=-5, xend = years, y = year_1, yend = year_2, col = coloring), size=.75) +
  
  # Horizontal line for 1818
  
  geom_vline(xintercept=-5, linetype="dashed", size=.1) + 
  
  # Horizontal line for 1908
  
  geom_vline(xintercept=90, linetype="dashed", size=.1) +
  
  # Remove the panel background
  
  theme(panel.background = element_blank()) +
  
  # Remove the grid
  
  theme(panel.grid=element_blank()) +
  
  # Remove the axis tickts
  
  theme(axis.ticks=element_blank()) +
  
  # Remove the axis text
  
  theme(axis.text.x=element_blank()) +
  theme(panel.border=element_blank()) + 
  
  # Remove the legend
  
  theme(legend.position="none") +
  
  # Remove the x-axis label
  
  xlab("") + 
  
  # Add a y-axis label
  
  ylab("Percent forested") + 
  
  labs(title = "Change in forestation, Kostroma Province") +
  
  # Set the size of the graphic
  
  xlim((-25),(years+25)) +
  ylim(25,(100)) +
  
  # Add labels for districts in year 2
  
  geom_text_repel(label = l13,
            y = slope_data$year_2,
            x = years, 
            hjust=-0.2,
            size=2,
            segment.color = "grey50",
            direction = "y") +
  
  # Add labels for districts in year 1
  
  geom_text_repel(label = l11,
            y = slope_data$year_1,
            x = -5, 
            hjust = 1.2,
            size=2,
            segment.color = "grey50",
            direction = "y") +
  
  # Add points for 1818
  
  geom_point(aes(x = -5, y = year_1, col = coloring)) +
  
  # Add points for 1908
  
  geom_point(aes(x = 90, y = year_2, col = coloring)) +
  
  # Add 1818 label
  
  geom_text(label="1818", 
            x=-7, 
            y=98,
            hjust= 1.2,size=5) +
  
  # Add 1908 label
  
  geom_text(label="1908", 
            x=105, 
            y=98,
            hjust= 1.2,size=5) +

  # Coloring
  
   scale_color_manual(values = c("green"="#00ba38", 
                                 "red"="#ff250d", 
                                 "dark red" = "#c91400", 
                                 "light red" = "#ff8989")) 



```


