---
title: "species_graphic"
author: "Miranda Lupion"
date: "1/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
library(readr)
library(tidyverse)
library(RColorBrewer)
library(ggrepel)
library(scales)
species_data <- read_csv("species.csv")

```


```{r production of data sets}

# Data prep for buysky district

buysky <- subset(species_data, district == "Buysky District", drop = FALSE) %>%
  filter(tree_species != "total_conifer") %>%
  filter(tree_species != "total_deciduous") %>%
  select(-type, -district) %>%
  mutate(total_trees = sum(quantity), percent_species =     round((quantity*100/total_trees)))%>%
  select(tree_species, percent_species) %>%
  spread(tree_species, percent_species) 

# To get us to 100 round up from .4

buysky$aspen <- 1

kologrivsky <- subset(species_data, district == "Kologrivsky District", drop = FALSE) 
vetluzhsky <- subset(species_data, district == "Vetluzhsky District", drop = FALSE) 
varnavinsky <- subset(species_data, district == "Varnavinsky District", drop = FALSE) 
makaryevsky <- subset(species_data, district == "Makaryevsky District", drop = FALSE) 
soligalichsky <- subset(species_data, district == "Soligalichsky District", drop = FALSE) 
chukhlomsky <- subset(species_data, district == "Chukhlomsky District", drop = FALSE) 
galichsky <- subset(species_data, district == "Galichsky District", drop = FALSE) 
kineshmasky <- subset(species_data, district == "Kineshmasky District", drop = FALSE) 
kostromsky <- subset(species_data, district == "Kostromsky District", drop = FALSE) 
yurevetsky <- subset(species_data, district == "Yurevetsky District", drop = FALSE) 
nerekhtsky <- subset(species_data, district == "Nerekhtsky District", drop = FALSE) 



```

```{r build waffle chart}
nrows <- 10
df_buysky <- expand.grid(y = 1:nrows, x = 1:nrows)
df_buysky$category <- factor(rep(names(buysky), buysky))

cols <- c("seagreen1", "seagreen3", "seagreen4", "slateblue4", "skyblue3", "slategray3", "navy")

ggplot(df_buysky, aes( x = x, y = y , fill = category)) +
  geom_tile(color = "snow3", size = 0.5) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), trans = 'reverse') +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(x = NULL, 
       y = NULL, 
       title = "Tree species in Buysky District",
       subtitle = "Kostroma Province",
       caption = "Where each box is a percent and figures are rounded to the nearest percent") +
  guides(fill = guide_legend(title = "Species")) +
  scale_fill_manual(labels = c("Aspen", "Birch", "Birch and Alder", "Birch and Aspen", "Pine", "Spruce", "Spruce and Pine"), values = cols) 

```

```{r pie chart}
pie_buysky <- buysky %>%
  gather(key, value) %>%
  filter(value > 0) %>%  
  
  # Assigning label positions
  
mutate(y_pos = (case_when(key == "aspen" ~ 100,
                        key == "birch" ~  97,
                        key == "birch_and_alder" ~ 94,
                      key == "birch_and_aspen" ~ 75,
                      key == "pine" ~ 60,
                      key =="spruce" ~ 40,
                      key == "spruce_and_pine" ~ 20))) %>%
  
mutate(x_pos = (case_when(key == "aspen" ~ 1.6,
                          key == "birch" ~ 1.6,
                         key == "birch_and_alder" ~ 1.6,
                         key == "birch_and_aspen" ~ 1.7,
                         key == "pine" ~ 1.65,
                         key =="spruce" ~ 1.65,
                          key == "spruce_and_pine" ~ 1.55)))  


pie_chart <- ggplot(pie_buysky, aes(x = 1, y=value, fill = key)) + 
  
  geom_bar(width = 1, stat = "identity") +
  
  theme(axis.line = element_blank(), 
        plot.title = element_text(hjust=0),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.background = element_blank(),
        panel.grid = element_blank()
        ) + 
  
  labs(fill="key", 
       x=NULL, 
       y=NULL, 
       title="Tree species in Buysky District", 
       subtitle = "Kostroma Province",
       caption="As a percent of total forested land") +
  
   
  coord_polar(theta = "y", start=0) +
  
  guides(fill = guide_legend(title = "Species")) +
  
  scale_fill_manual(labels = c("Aspen", "Birch", "Birch and Alder", "Birch and Aspen", "Pine", "Spruce", "Spruce and Pine"), values = cols) +
  geom_text(label = paste0(pie_buysky$value, "%"),
                  x = pie_buysky$x_pos, 
                  y = pie_buysky$y_pos,
                  hjust = 0,
                  size = 2.5,
                  segment.color = "grey50",
                  direction = "x") 
 

pie_chart


  



```

```{r dot plot}

cols <- c("seagreen1", "seagreen3", "seagreen4", "slateblue4", "skyblue3", "slategray3", "navy", "slateblue2", "seagreen2")


dot_plot <- species_data %>%
  filter(district != "total_deciduous", 
         district != "total_conifer", 
         district != "All", 
         district != "Total for southwest",
         district != "Total for northeast",
         district != "Total for southeast") %>%
  filter(tree_species != "total_conifer",
         tree_species != "total_deciduous",
         tree_species != "other_conifers",
         tree_species != "other_deciduous") %>%
  mutate(tree_species = case_when(tree_species == "alder" ~ "Alder", 
                                  tree_species == "aspen" ~ "Aspen", 
                                  tree_species == "birch" ~ "Birch", 
                                  tree_species == "birch_and_alder" ~ "Birch and Alder", 
                                  tree_species == "birch_and_aspen" ~ "Birch and Aspen",
                                  tree_species == "pine" ~ "Pine",
                                  tree_species == "spruce" ~ "Spruce",
                                  tree_species == "spruce_and_fir" ~ "Spruce and Fir", 
                                  tree_species == "spruce_and_pine" ~ "Spruce and Pine")) %>%
  mutate(district = str_remove(district, " District"))



  # can filter for a specific district to only make a dot plot of that. Can also use facet wrap to compare them all

dot_plot_var <- dot_plot %>%
  filter(district == "Varnavinsky") 
  
# For ordering

dot_plot_var <- dot_plot_var[order(dot_plot_var$quantity), ]  
dot_plot_var$tree_species <- factor(dot_plot_var$tree_species, levels = dot_plot_var$tree_species)
  
ggplot(dot_plot_var, aes(x = tree_species, y = quantity, color = tree_species)) +
  geom_point(size = 3) +
  geom_segment(aes(x = tree_species, 
                   xend = tree_species, 
                   y = min(quantity), 
                   yend = max(quantity)), 
               linetype="dashed", 
               size=0.1) +
  coord_flip() +
  # facet_wrap(~district, nrow = 2, ncol = 6) +
  labs(title="Tree Species in Varnavinsky District, Kostroma Province", 
       subtitle="Species counts", 
       caption="Caption here",
       x = "Species",
       y = "Quantity")  +
  scale_color_manual(labels = c("Alder", "Aspen", "Birch", "Birch and Alder", "Birch and Aspen", "Pine", "Spruce", "Spruce and Fir", "Spruce and Pine"), values = cols) +
  theme(legend.position="none") +
  
  # Force out of scientific notation
  
  scale_y_continuous(labels = comma)

```

